version: '3.1'
services:
  coach-finder-server:
    build: .
    container_name: coach-finder-server
    ports:
      - "8080:8080"
    depends_on:
      - coach-finder-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://coach-finder-db:5432/coach-finder
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DRIVER=org.postgresql.Driver

  coach-finder-db:
    image: postgres:14-alpine
    container_name: coach-finder-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=coach-finder
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DRIVER=org.postgresql.Driver